142682 - BESS CS Create Mock Endpoint for File Upload
UKHO/periodic-output-service pull request #128
Opened 2024-03-01 07:34 UTC by shailen14599

PBI consists changes of [PBI 142682](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/142682)

- Code changes to create a mock endpoint to upload BESS configuration files to azure storage
- Added functional tests

2024-03-04 07:07 UTC, shirinbt14926 requested changes
Few Comments to address

2024-03-04 07:07 UTC, shirinbt14926 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/UploadBessConfigFileTests.cs
> +        public async Task WhenICallUploadConfigApiWithValidConfigFile_ThenCreatedStatusCodeIsReturned()
We can rename test case either as
       ` public async Task WhenICallUploadConfigApiWithValidConfigFile_Then201StatusCodeIsReturned()`
 or
        `public async Task WhenICallUploadConfigApiWithValidConfigFile_ThenCreatedStatusIsReturned()`

2024-03-04 07:07 UTC, shirinbt14926 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/UploadBessConfigFileTests.cs
> +        public async Task WhenICallUploadConfigApiWithInvalidConfigFile_ThenCreatedStatusCodeIsReturned()
```suggestion
        public async Task WhenICallUploadConfigApiWithInvalidConfigFile_ThenBadRequestStatusCodeIsReturned()
```
as invalid config file will give 400-Bad Request

2024-03-04 07:24 UTC, Arit14975 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/UploadBessConfigFileTests.cs
> +        public async Task WhenICallUploadConfigApiWithInvalidConfigFile_ThenCreatedStatusCodeIsReturned()
Resolved. Thanks

2024-03-04 07:24 UTC, Arit14975 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/Models/BESSConfigModel.cs
> +    public class Tag
Resolved. Thanks

2024-03-04 07:25 UTC, Arit14975 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/UploadBessConfigFileTests.cs
> +            HttpResponseMessage apiResponse = await BessUploadFileHelper.UploadConfigFile(testConfiguration.bessConfig.BaseUrl, @"./TestData/InvalidConfigFile.json");
Resolved. Thanks

2024-03-04 07:25 UTC, Arit14975 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/UploadBessConfigFileTests.cs
> +            HttpResponseMessage apiResponse = await BessUploadFileHelper.UploadConfigFile(testConfiguration.bessConfig.BaseUrl, @"./TestData/configFile.json");
Resolved. Thanks

2024-03-04 08:48 UTC, shailen14599 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Controllers/MockController.cs
> +        private readonly AzureStorageService _azureStorageService;
Resolved

2024-03-04 13:14 UTC, Mayuresh-Gawde commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/Helpers/TestConfiguration.cs
> +            public string? InvalidConfigPath { get; set; }
Resolved

2024-03-04 13:30 UTC, shirinbt14926 approved these changes
LGTM. Thanks @Arit14975  and @shailen14599

2024-03-04 13:34 UTC, Mayuresh-Gawde approved these changes
LGTM from QA!!

2024-03-04 13:48 UTC, harshal11869 approved these changes
Looks Good.

2024-03-05 13:06 UTC, amogh14893 approved these changes
Reviewed changes for YAML , LGTM.

2024-03-06 12:30 UTC, DanOwenUKHO approved these changes
LGTM

2024-03-07 12:39 UTC, merged