142689 - BESS Builder Service WebJob Logging and Configuration
UKHO/periodic-output-service pull request #130
Opened 2024-03-05 07:20 UTC by rupali15127

This PR consists code changes of [PBI 142689](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/142689)

Kindly review the same.

2024-03-05 14:25 UTC, harshal11869 requested changes

2024-03-05 14:25 UTC, harshal11869 commented on UKHO.PeriodicOutputService/UKHO.BESS.BuilderService/Program.cs
> +        private static readonly string s_assemblyVersion = Assembly.GetExecutingAssembly().GetCustomAttributes<AssemblyFileVersionAttribute>().Single().Version;
```suggestion
        private static readonly InMemoryChannel aiChannel = new();
        private static readonly string assemblyVersion = Assembly.GetExecutingAssembly().GetCustomAttributes<AssemblyFileVersionAttribute>().Single().Version;
```

2024-03-05 14:25 UTC, harshal11869 commented on UKHO.PeriodicOutputService/UKHO.BESS.BuilderService/BessBuilderServiceJob.cs
> +        private readonly ILogger<BessBuilderServiceJob> logger;
Add one blank after line no. 9

2024-03-06 05:26 UTC, rupali15127 commented on UKHO.PeriodicOutputService/UKHO.BESS.BuilderService/BessBuilderServiceJob.cs
> +        private readonly ILogger<BessBuilderServiceJob> logger;
Resolved.

2024-03-06 05:26 UTC, rupali15127 commented on UKHO.PeriodicOutputService/UKHO.BESS.BuilderService/Program.cs
> +        private static readonly string s_assemblyVersion = Assembly.GetExecutingAssembly().GetCustomAttributes<AssemblyFileVersionAttribute>().Single().Version;
Resolved

2024-03-06 05:43 UTC, harshal11869 approved these changes
LGTM.

2024-03-06 07:17 UTC, Nadeem14456 approved these changes
LGTM.

2024-03-06 11:35 UTC, Mayuresh-Gawde approved these changes
LGTM from QA!!

2024-03-08 19:11 UTC, merged