140034 - BESS CS - Get AVCS Catalogue from SCS
UKHO/periodic-output-service pull request #131
Opened 2024-03-08 08:02 UTC by ratnas104142

This PR consists changes of [PBI 140034](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/140034) :

- Code changes for getting AVCS catalogue data from SCS for BESS Configuration Service
- Added unit tests
- Added functional tests

2024-03-11 07:50 UTC, Nadeem14456 requested changes

2024-03-11 07:50 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/ISalesCatalogueService.cs
> +using System.Text;
remove unused usings.

2024-03-11 07:50 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SCSGetSalesCatalogueDataRequestStarted = 809110,
```suggestion
        ScsGetSalesCatalogueDataRequestStarted = 809110,
```

2024-03-11 07:50 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SCSGetSalesCatalogueDataRequestCompleted = 809111,
```suggestion
        ScsGetSalesCatalogueDataRequestCompleted = 809111,
```

2024-03-11 07:50 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SalesCatalogueServiceCatalogueDataNonOkResponse = 809112,
```suggestion
        ScsGetSalesCatalogueDataNonOkResponse = 809112,
```

2024-03-11 07:52 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        RetryHttpClientSCSRequest = 809113,
```suggestion
        RetryHttpClientScsRequest = 809113,
```

2024-03-11 10:23 UTC, harshal11869 requested changes

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Models/Scs/Response/SalesCatalogueDataResponse.cs
> +        }
Resolved!

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/SalesCatalogueClient.cs
> +        }
Resolved!

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Helpers/SalesCatalogueClient.cs
> +            httpRequestMessage.Headers.Authorization = new AuthenticationHeaderValue("Bearer", authToken);
Resolved!

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SalesCatalogueServiceCatalogueDataNonOkResponse = 809112,
Resolved!

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SCSGetSalesCatalogueDataRequestCompleted = 809111,
Resolved!

2024-03-11 11:05 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        SCSGetSalesCatalogueDataRequestStarted = 809110,
Resolved!

2024-03-11 11:06 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Services/ISalesCatalogueService.cs
> +using System.Text;
Resolved!

2024-03-11 11:06 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService.UnitTests/Services/SalesCatalogueServiceTests.cs
> +                    new SalesCatalogueDataProductResponse()
Resolved!

2024-03-11 11:06 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService.UnitTests/Services/ConfigurationServiceTests.cs
> +                    new SalesCatalogueDataProductResponse
Resolved!

2024-03-11 11:06 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/appsettings.json
> +    "SalesCatalogue": {
Resolved!

2024-03-11 11:06 UTC, ratnas104142 commented on UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/appsettings.local.overrides.json
> +    "SalesCatalogue": {
Resolved!

2024-03-11 13:43 UTC, harshal11869 requested changes

2024-03-11 13:43 UTC, harshal11869 commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/Helpers/AuthTokenProvider.cs
> +        static string? ScsAccessToken;
Any reason to make string nullable? As string accepts null as well.

2024-03-11 13:49 UTC, Nadeem14456 approved these changes
LGTM.

2024-03-11 13:58 UTC, harshal11869 approved these changes
LGTM.

2024-03-11 13:58 UTC, Mayuresh-Gawde approved these changes
LGTM from QA!!

2024-03-12 16:07 UTC, DanOwenUKHO approved these changes

2024-03-12 16:53 UTC, merged