142688 - Bess Configuration Service get enccellname from prefix patterns
UKHO/periodic-output-service pull request #133
Opened 2024-03-13 08:00 UTC by MastekRohitChettri

This PR consists changes of [PBI : 142688](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/142688)

2024-03-18 09:39 UTC, harshal11869 requested changes

2024-03-18 11:05 UTC, shirinbt14926 reviewed
Minor comments please

2024-03-19 05:31 UTC, MastekRohitChettri commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/Logging/EventIds.cs
> +        /// 809120 - Listed cells or pattern not found in catalog
Resolved

2024-03-19 05:31 UTC, MastekRohitChettri commented on UKHO.PeriodicOutputService/UKHO.BESS.ConfigurationService/Services/ConfigurationService.cs
> +            #region filter provided prefix patterns
Resolved

2024-03-19 05:33 UTC, MastekRohitChettri commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Common/UKHO.PeriodicOutputService.Common.csproj
> +    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.3" />
Got issues with packages when took develop branch so reinstall latest package also there is unnecessary package was used which we removed (<PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />)

2024-03-19 09:09 UTC, harshal11869 approved these changes
Looks Good.

2024-03-19 09:26 UTC, Nadeem14456 approved these changes
LGTM.

2024-03-19 12:57 UTC, DanOwenUKHO approved these changes

2024-03-20 13:51 UTC, shirinbt14926 approved these changes
Looks good

2024-03-20 15:46 UTC, merged