140038 - Bess Builder Service AD authorization for Ess and Fss API
UKHO/periodic-output-service pull request #138
Opened 2024-03-25 08:27 UTC by rupali15127

This PR consists changes of [PBI 140038](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/140038) and [PBI 140032](https://dev.azure.com/ukhydro/Exchange%20Set%20Service/_workitems/edit/140032)

- Code changes for ad auth for ess and fss api
- Unit test cases 
- Mocks related changes in FSS and ESS for BESS
- Added functional tests

2024-03-27 11:11 UTC, rsj-github requested changes
in general hard coding isn't best practice and leads to fragility

2024-03-27 11:11 UTC, rsj-github commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/EssIntegration/EssIntegrationTests.cs
> +            dataHelper.GetProductVersionData("GB301910", 1, 0)
hard coding

2024-03-27 12:42 UTC, shirinbt14926 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Controllers/ExchangeSetServiceController.cs
> +                }
Same as previous comment

2024-03-27 12:42 UTC, shirinbt14926 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Controllers/ExchangeSetServiceController.cs
> +                }
Same as previous comment

2024-03-27 12:53 UTC, Mayuresh-Gawde commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/EssIntegration/EssIntegrationTests.cs
> +        protected List<string> productIdentifiers = new() { "GB301910" };
Resolved!!

2024-03-27 12:54 UTC, Mayuresh-Gawde commented on UKHO.PeriodicOutputService/UKHO.BESS.API.FunctionalTests/FunctionalTests/EssIntegration/EssIntegrationTests.cs
> +            dataHelper.GetProductVersionData("GB301910", 1, 0)
Resolved!!

2024-03-28 08:35 UTC, harshal11869 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Services/ExchangeSetService.cs
>              if (productIdentifiers.Contains("GB800001") ||
This is mock service and mainly this hardcoded cells differentiate the request is for AIO or No AIO and it also get utilized by both POS & POS AIO services.

2024-03-28 10:08 UTC, Nadeem14456 commented on UKHO.PeriodicOutputService/UKHO.BESS.BuilderService/appsettings.json
> +        "Service": "BESS Configuration Service",
```suggestion
        "Service": "BESS Builder Service",
```

2024-03-28 10:18 UTC, harshal11869 approved these changes
Looks Good.

2024-03-28 11:20 UTC, rsj-github approved these changes

2024-03-28 11:53 UTC, JiviteshT approved these changes
Looks good

2024-03-28 11:53 UTC, merged