152477 PKS Wiremock Service
UKHO/periodic-output-service pull request #151
Opened 2024-04-29 11:09 UTC by shirinbt14926

Added PKS post endpoint with wiremock in POS
Devops changes

2024-04-30 06:03 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/IWireMockService.cs
> +
```suggestion
namespace UKHO.PKSWireMock.API
{
    public interface IWireMockService
    {
        void Start();

        void Stop();
    }
}

```

2024-04-30 06:59 UTC, Nadeem14456 requested changes

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/IWireMockService.cs
> +
inconsistent spacing 
```suggestion
﻿namespace UKHO.PKSWireMock.API
{
    public interface IWireMockService
    {
        void Start();

        void Stop();
    }
}

```

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/App.cs
> +    public class App :IHostedService
```suggestion
    public class App : IHostedService
```

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/App.cs
Avoid the use of underscore for private fields

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/WireMockService.cs
Avoid the use of underscore for private fields

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/WireMockService.cs
> +
remove blank space

2024-04-30 06:59 UTC, Nadeem14456 commented on UKHO.PKSWireMockService.API/WireMockService.cs
> +            }
```suggestion
            using var fileStream = new StreamReader(filePath);
return  fileStream .ReadToEnd();
```

2024-04-30 07:53 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/WireMockService.cs
> +
Done

2024-04-30 07:53 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/WireMockService.cs
Done

2024-04-30 07:54 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/App.cs
Done

2024-04-30 07:55 UTC, amogh14893 approved these changes
Reviewed DevOps changes. LGTM

2024-04-30 07:58 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/IWireMockService.cs
> +
Done

2024-04-30 07:59 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/App.cs
> +    public class App :IHostedService
Done

2024-04-30 12:10 UTC, shirinbt14926 commented on UKHO.PKSWireMockService.API/WireMockService.cs
> +            }
Done

2024-04-30 13:35 UTC, Nadeem14456 approved these changes

2024-05-02 09:45 UTC, DanOwenUKHO approved these changes

2024-05-02 10:49 UTC, merged