56279 - pos batch file attributes changes
UKHO/periodic-output-service pull request #44
Opened 2022-09-14 16:12 UTC by Vishal14583

Remove Batch Type from attributes for all batches.
Remvoe S63 version for catalogue and ENC Update batch.
Add file details like MimeType, FileSize in stubs etc.
Add file name in file attribute list for all batches.

2022-09-15 13:17 UTC, harshal11869 requested changes

2022-09-15 13:17 UTC, harshal11869 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FssService.cs
> +            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration)); ;
```suggestion
            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration));
```

2022-09-15 14:19 UTC, mattwin1 requested changes

2022-09-15 14:51 UTC, sumod13943 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Helpers/FileHelper.cs
> +            using Stream? fs = fileInfo.OpenRead();
Changed

2022-09-15 14:51 UTC, sumod13943 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/GetBatchDetails.cs
>              if (mediaType.Equals("Zip"))
Changed

2022-09-15 14:51 UTC, sumod13943 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.Fulfilment/Services/FssService.cs
> +            _configuration = configuration ?? throw new ArgumentNullException(nameof(configuration)); ;
Changed

2022-09-15 14:52 UTC, sumod13943 commented on UKHO.PeriodicOutputService/UKHO.PeriodicOutputService.API.FunctionalTests/Helpers/FileContentHelper.cs
>              if (mediaType.Equals("Zip"))
Changed

2022-09-15 16:13 UTC, harshal11869 approved these changes
Looks Good

2022-09-15 16:15 UTC, surendrabehara2022 commented on azure-pipelines.yml
> +                    arguments: '-essapibaseurl $(ESSApiConfiguration.BaseUrl_PostFT) -fssapibaseurl $(FSSApiConfiguration.BaseUrl_PostFT) -fleetmanagerbaseurl $(FleetManagerB2BApiConfiguration.BaseUr
Hi Matt,
I have hardcoded the values "true" and "false" instead of referring from library variables.

2022-09-16 07:29 UTC, ajasonca approved these changes
Looks good

2022-09-16 07:43 UTC, mattwin1 approved these changes
LGTM

2022-09-16 09:15 UTC, ajasonca approved these changes

2022-09-16 13:14 UTC, merged