WIP - 74473 - aio weeks update output batches in fss
UKHO/periodic-output-service pull request #78
Opened 2023-05-11 15:06 UTC by sumod13943

Following changes are part of the branch
1) Creation of AIO Update exchange sets
2) Parallel execution of both AIO BASE CD and AIO Update
3) Unit tests
4) Functional tests - (minor fixes remaining)

2023-05-12 09:24 UTC, DanOwenUKHO requested changes
A small comment to resolve

2023-05-12 09:24 UTC, DanOwenUKHO commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Services/ExchangeSetService.cs
> +                //string productVersion = $"productVersion-{item.ProductName}-{item.EditionNumber}-{item.UpdateNumber}";
Delete commented code

2023-05-12 13:32 UTC, sumod13943 commented on UKHO.FmEssFssMock.API/UKHO.FmEssFssMock.API/Services/ExchangeSetService.cs
> +                //string productVersion = $"productVersion-{item.ProductName}-{item.EditionNumber}-{item.UpdateNumber}";
Deleted

2023-05-12 13:34 UTC, DanOwenUKHO approved these changes

2023-05-15 07:36 UTC, ray-sj approved these changes
looks fine

2023-05-15 09:31 UTC, merged